### ISSUE TITLE
localhost address not working for Node-RED and Groov Server on same machine

### ISSUE THREAD

**Issue by jturner-22** [Opto22/node-red-contrib-groov#1]
Using "localhost" for Groov's address does not work when Node-RED and Groov Server are on the same machine.

Node-RED will show an error like *[error] [groov-read-ds:get station] Connection refused. Error code: ECONNREFUSED from system call "connect"*

**Comment by mohiji** [comment]
It looks like this is due to groov not using the default ports internally, right? Would be better to just ask people to provide a full URL with port?

**Comment by optodeveloper** [comment]
localhost is found in /etc/resolv.conf.  We could add anything we want to
this file and have it load the correct address.  For example "groov" could
point to "127.0.0.1:8443".

On Wed, Jan 11, 2017 at 3:37 PM Jonathan Fischer <notifications@github.com>
wrote:

It looks like this is due to groov not using the default ports internally,
right? Would be better to just ask people to provide a full URL with port?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Opto22/node-red-contrib-groov/issues/1#issuecomment-272030774>,
or mute the thread

**Comment by mohiji** [comment]
No, that won't work: /etc/resolv.conf is only for name resolution, ports don't apply.

Somewhat pedantically speaking, the proper answer is to use fully qualified domain names, not localhost. https://localhost is guaranteed to give you SSL certificate errors, regardless of whether the customer has a valid, trusted certificate installed: the name on the certificate is never going to be localhost.  But if they have a certificate for say, demo.groov.com, https://demo.groov.com is always going to work, and since you're not connecting directly over the loopback interface anymore, it works around our slightly weird firewall configuration.

Alternatively, we could tweak the firewall on the AR-1 to forward 443 on the loopback interface to 8443. I think that's how we're handling 443 on the external interface currently, right?

**Comment by jturner-22** [comment]
Fixed in version 1.0.1
